export const GENRES = [
  { name: 'Hài Hước', slug: 'hai-huoc' },
  { name: 'Gia Đình', slug: 'gia-dinh' },
  { name: 'Hành Động', slug: 'hanh-dong' },
  { name: 'Hình Sự', slug: 'hinh-su' },
  { name: 'Kinh Dị', slug: 'kinh-di' },
  { name: 'Cổ Trang', slug: 'co-trang' },
  { name: 'Võ Thuật', slug: 'vo-thuat' },
  { name: 'Short Drama', slug: 'short-drama' },
  { name: 'Tình Cảm', slug: 'tinh-cam' },
  { name: 'Tài Liệu', slug: 'tai-lieu' },
  { name: 'Tâm Lý', slug: 'tam-ly' },
  { name: 'Âm Nhạc', slug: 'am-nhac' },
  { name: 'Thể Thao', slug: 'the-thao' },
  { name: 'Chiến Tranh', slug: 'chien-tranh' },
  { name: 'Thần Thoại', slug: 'than-thoai' },
  { name: 'Học Đường', slug: 'hoc-duong' },
  { name: 'Kinh Điển', slug: 'kinh-dien' },
  { name: 'Hoạt hình', slug: 'hoat-hinh' },
  { name: 'Chiếu rạp', slug: 'chieu-rap' },
  { name: 'Action', slug: 'action' },
  { name: 'Adventure', slug: 'adventure' },
  { name: 'Sci-Fi', slug: 'sci-fi' },
  { name: 'Fantasy', slug: 'fantasy' },
  { name: 'Giả Tưởng', slug: 'gia-tuong' },
  { name: 'Phim Hài', slug: 'phim-hai' },
  { name: 'Khoa Học Viễn Tưởng', slug: 'khoa-hoc-vien-tuong' },
  { name: 'Lãng Mạn', slug: 'lang-man' },
  { name: 'Gây Cấn', slug: 'gay-can' },
  { name: 'Lịch Sử', slug: 'lich-su' },
  { name: 'Trẻ Em', slug: 'tre-em' },
  { name: 'Phim 18+', slug: 'phim-18' },
  { name: 'Hài', slug: 'hai' },
  { name: 'Chính Kịch', slug: 'chinh-kich' },
  { name: 'Bí Ẩn', slug: 'bi-an' },
  { name: 'Viễn Tưởng', slug: 'vien-tuong' },
  { name: 'Khoa Học', slug: 'khoa-hoc' },
  { name: 'Phiêu Lưu', slug: 'phieu-luu' },
  { name: 'Reality', slug: 'reality' },
  { name: 'Talk', slug: 'talk' },
  { name: 'Phim Nhạc', slug: 'phim-nhac' },
  { name: 'Phim Ngắn', slug: 'phim-ngan' },
  { name: 'Marvel', slug: 'marvel' },
  { name: 'Miền Tây', slug: 'mien-tay' },
];

export const COUNTRIES = [
  { name: 'Trung Quốc', slug: 'trung-quoc' },
  { name: 'Âu Mỹ', slug: 'au-my' },
  { name: 'Hàn Quốc', slug: 'han-quoc' },
  { name: 'Indonesia', slug: 'indonesia' },
  { name: 'Philippines', slug: 'philippines' },
  { name: 'Nga', slug: 'nga' },
  { name: 'Singapore', slug: 'singapore' },
  { name: 'Nhật Bản', slug: 'nhat-ban' },
  { name: 'Thái Lan', slug: 'thai-lan' },
  { name: 'Anh', slug: 'anh' },
  { name: 'Pháp', slug: 'phap' },
  { name: 'Hồng Kông', slug: 'hong-kong' },
  { name: 'Canada', slug: 'canada' },
  { name: 'Ấn Độ', slug: 'an-do' },
  { name: 'Na Uy', slug: 'na-uy' },
  { name: 'Đức', slug: 'duc' },
  { name: 'Việt Nam', slug: 'viet-nam' },
  { name: 'Thổ Nhĩ Kỳ', slug: 'tho-nhi-ky' },
  { name: 'Argentina', slug: 'argentina' },
  { name: 'Hà Lan', slug: 'ha-lan' },
  { name: 'Hy Lạp', slug: 'hy-lap' },
  { name: 'Brazil', slug: 'brazil' },
  { name: 'Đài Loan', slug: 'dai-loan' },
  { name: 'Mexico', slug: 'mexico' },
  { name: 'Nam Phi', slug: 'nam-phi' },
  { name: 'Colombia', slug: 'colombia' },
  { name: 'Đan Mạch', slug: 'dan-mach' },
  { name: 'Thụy Điển', slug: 'thuy-dien' },
  { name: 'Ukraina', slug: 'ukraina' },
  { name: 'Bồ Đào Nha', slug: 'bo-dao-nha' },
  { name: 'Malaysia', slug: 'malaysia' },
  { name: 'Thụy Sĩ', slug: 'thuy-si' },
  { name: 'Ireland', slug: 'ireland' },
  { name: 'Hungary', slug: 'hungary' },
  { name: 'Séc', slug: 'sec' },
];

export const YEARS: number[] = (() => {
  const current = new Date().getFullYear();
  const years: number[] = [];
  for (let y = current; y >= 2007; y--) years.push(y);
  return years;
})();
